### PR TITLE
Fix imports for new Hypothesis

### LINKED ISSUE #7: Require hypothesis <=5.5.0
Version 5.5.1 of hypothesis got rid of _GenericStateMachine, so hypothesis-trio no longer works.

### PR DESCRIPTION
**Pull request by Zac-HD**
Fixes #7.  CC @touilleMan - I think you're the only one who can do a release 😅

### CODE REVIEW

**Comment by touilleMan** [comment]
@Zac-HD from what I see on pypi, you're part of the maintainers (along with Nathaniel) ;-)

Regarding this PR, the copy/paste of `hypothesis.stateful.run_state_machine` should be updated
https://github.com/python-trio/hypothesis-trio/blob/df08e6fa60312f663785e20fe9e17b8e92c20d75/hypothesis_trio/stateful.py#L131-L192

(the CI is crashing given the copy/paste is of course totally dependent of the internal implementation of hypothesis...)

**Comment by Zac-HD** [comment]
> @Zac-HD from what I see on pypi, you're part of the maintainers (along with Nathaniel) ;-)

I have the credentials... and no idea how Trio's release system works.  For all my projects we just merge the PR and it's automatic after that!

**Comment by touilleMan** [comment]
> I have the credentials... and no idea how Trio's release system works

There is the cheatsheet to help you: https://github.com/python-trio/hypothesis-trio/blob/master/CHEATSHEET.rst

However, if you prefer, I can do the release myself once this PR is merged ;-)

**Comment by touilleMan** [comment]
I've updated this PR, this should work fine now.

However travis CI is broken, so we have to mirate to github action first before merging this :/

On top of that, https://github.com/HypothesisWorks/hypothesis/pull/3186 will require an additional change to correctly handle invariants display in falsifying example

**Comment by Zac-HD** [comment]
I think that's all the pre-requisites done 🚀 

Are you OK to rebase and finish this up?

**Comment by touilleMan** [comment]
@Zac-HD yup, I'm working on this ;-)

**Pull request merged**
